services:

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888 # HTTP proxy
      - 8388:8388 # Shadowsocks
      - 9696:9696 # Prowlarr
      - 8085:8085 # Qbit WebUI
      - 3005:3000 # Qbit RPC
    volumes:
      - /data/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS=Netherlands
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      timeout: 30s
      retries: 5
    restart: unless-stopped
    networks:
      media-server_default:
        ipv4_address: 172.18.0.2

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - '/data/configs/prowlarr:/config'
    restart: unless-stopped
    network_mode: service:gluetun

  qflood:
    container_name: qflood
    image: hotio/qflood
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
      - FLOOD_AUTH=false
      - WEBUI_PORTS=8085/tcp,8085/udp,3000/tcp,3000/udp
    volumes:
      - '/data/configs/qflood:/config'
      - '/data/torrents:/data/torrents'
    restart: unless-stopped
    network_mode: service:gluetun

  bazarr:
    container_name: bazarr
    image: ghcr.io/linuxserver/bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - '/data/configs/bazarr:/config'
      - '/data:/data'
    ports:
      - '6767:6767'
    restart: unless-stopped
    networks:
      media-server_default:
        ipv4_address: 172.18.0.3

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    ports:
      - '8989:8989'
    volumes:
      - '/data/configs/sonarr:/config'
      - '/data:/data'
    restart: unless-stopped
    networks:
      media-server_default:
        ipv4_address: 172.18.0.8

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    ports:
      - '7878:7878'
    volumes:
      - '/data/configs/radarr:/config'
      - '/data:/data'
    restart: unless-stopped
    networks:
      media-server_default:
        ipv4_address: 172.18.0.7

  jellyfin:
    container_name: jellyfin
    image: ghcr.io/linuxserver/jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    ports:
      - '8096:8096'
    devices:
      - '/dev/dri/renderD128:/dev/dri/renderD128'
      - '/dev/dri/card0:/dev/dri/card0'
    volumes:
      - '/data/configs/jellyfin:/config'
      - '/data/media:/data/media'
    restart: unless-stopped
    networks:
      media-server_default:
        ipv4_address: 172.18.0.9

  ombi:
    container_name: ombi
    image: ghcr.io/linuxserver/ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - '/data/configs/ombi:/config'
    ports:
      - '3579:3579'
    restart: unless-stopped
    networks:
      media-server_default:
        ipv4_address: 172.18.0.5


  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    ports:
      - '8191:8191'
    restart: unless-stopped
    networks:
      media-server_default:
        ipv4_address: 172.18.0.4

  heimdall:
    container_name: heimdall
    image: ghcr.io/linuxserver/heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - '/server/configs/heimdall:/config'
    ports:
      - '8090:80'
    restart: unless-stopped
    networks:
      media-server_default:
        ipv4_address: 172.18.0.6


networks:
  media-server_default:
    external: true
